### ISSUE TITLE
GoogleAdsService.search returns InternalServerError for large WHERE filters

### ISSUE THREAD

**Issue by wesleybowman** [googleads/google-ads-python#104]
When querying the `GoogleAdsService`, if the values in a WHERE filter exceed 15,000 items, then you can consistently get an `InternalServerError`.

An example query:

```python
    query = f"""
        SELECT
            ad_group.id,
            ad_group_ad.ad.id,
            ad_group_ad.ad.expanded_text_ad.headline_part1,
            ad_group_ad.ad.expanded_text_ad.headline_part2,
            ad_group_ad.ad.expanded_text_ad.headline_part3,
            ad_group_ad.ad.expanded_text_ad.description,
            ad_group_ad.ad.expanded_text_ad.description2,
            ad_group_ad.ad.expanded_text_ad.path1,
            ad_group_ad.ad.expanded_text_ad.path2,
            ad_group_ad.ad.final_urls,
            ad_group_ad.ad.type,
            ad_group_ad.status
        FROM ad_group_ad
        WHERE ad_group.id IN {google_adgroup_ids_tuple}
    """
```

where `google_adgroup_ids_tuple` is a tuple of ids. 

At the very least, I wouldn't expect to get an InternalServerError here. I would expect a more informative error. I only found this issue through trail and error (after having a hunch that it might be because the query is too big).

**Comment by BenRKarl** [comment]
@wesleybowman Thanks for the question! Agreed InternalServerError isn't very helpful. Do you happen to have a request-id from the response logs?

**Comment by samphippen** [comment]
@BenRKarl @wesleybowman I've filed an internal bug within google for this issue!

**Comment by wesleybowman** [comment]
> Do you happen to have a request-id from the response logs?

@BenRKarl I recreated an example in our test account, just by pushing 20k adgroups to a campaign (and those adgroups have ads in them). I then ran the query, and got the following from the logs:


```
Response
-------
Headers: {
  "request-id": "6FwUEix4v-T1ACqKalvz8Q"
}
Fault: {
  "created": "@1557469495.914371308",
  "description": "Error received from peer ipv4:172.217.17.106:443",
  "file": "src/core/lib/surface/call.cc",
  "file_line": 1041,
  "grpc_message": "Internal error encountered.",
  "grpc_status": 13
}
```

**Comment by jesusenlanet** [comment]
Hi all,
In my case the query I'm doing it's quite simple:

```
SELECT 
    campaign.id, 
    campaign.name, 
    campaign_budget.amount_micros, 
    customer.currency_code 
FROM campaign 
ORDER BY campaign.id
```

Logs:
```
Method: /google.ads.googleads.v1.services.GoogleAdsService/Search
Host: googleads.googleapis.com:443
Headers: {
  "developer-token": "REDACTED",
  "login-customer-id": "XXXXXXXXX",
  "x-goog-api-client": "gl-python/2.7.10 grpc/1.20.1 gax/1.10.0 gapic/2.0.0"
}
Request: {
  "query": "SELECT campaign.id, campaign.name, campaign_budget.amount_micros, customer.currency_code FROM campaign ORDER BY campaign.id",
  "customerId": "XXXXXXX"
}

Response
-------
Headers: {
  "request-id": "YIVpw_P3U9ycrj-94sDQTQ"
}
Fault: {
  "created": "@1557935192.939434000",
  "description": "Error received from peer ipv4:172.217.168.170:443",
  "file": "src/core/lib/surface/call.cc",
  "file_line": 1041,
  "grpc_message": "Internal error encountered.",
  "grpc_status": 13
}

[2019-05-15 17:46:32 - WARNING] Request made: ClientCustomerId:XXXXXXX, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v1.services.GoogleAdsService/Search, RequestId: None, IsFault: True, FaultMessage: Internal error encountered.
Traceback (most recent call last):
  File "src/test_get_all_accounts.py", line 86, in <module>
  File "src/test_get_all_accounts.py", line 67, in main
  File "/path/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 204, in _items_iter
    for page in self._page_iter(increment=False):
  File "/path/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 235, in _page_iter
    page = self._next_page()
  File "/path/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 526, in _next_page
    response = self._method(self._request)
  File "/path/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/path/lib/python2.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/path/lib/python2.7/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/path/lib/python2.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/path/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/path/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
google.api_core.exceptions.InternalServerError: 500 Internal error encountered.
```

I post this in case anyone find it useful.

Lot of thanks.

**Comment by wesleybowman** [comment]
@jesusenlanet For your query, do you get an internal server error **every** time you run it? 

We see internal server errors all the time, but most of the time a simple retry will fix the issue. We use exponential retries for our queries. The query this issue was created for consistently gave us internal server errors.

**Comment by jesusenlanet** [comment]
Hi @wesleybowman 

It was happening all the afternoon, but today it's working fine.
Thanks for the clarification, I will add a retry and keep it monitored to see how it works.

Thanks.

**Comment by wihl** [comment]
closing as obsolete. Reopen if necessary.
