### ISSUE TITLE
Can't set targetCpa for campaign level

### ISSUE THREAD

**Issue by rromio** [googleads/google-ads-python#175]
Hi!

I work with Python 3.7, use library v201809. I get from google ads api targetCpa for campaign:
{
            'id': 6465276842,
            ...
            'biddingStrategyConfiguration': {
                'biddingStrategyId': None,
                'biddingStrategyName': None,
                'biddingStrategyType': 'TARGET_CPA',
                'biddingStrategySource': None,
                'biddingScheme': {
                    'BiddingScheme.Type': 'TargetCpaBiddingScheme',
                    'targetCpa': {
                        'ComparableValue.Type': 'Money',
                        'microAmount': 54000000
                    },
                    'maxCpcBidCeiling': None,
                    'maxCpcBidFloor': None
                },
                'bids': [],
                'targetRoasOverride': None
            },
           ...
        }

Then I try to set new value for 'targetCpa' with this part of code:
{'operator': 'SET',
            'operand': {
                'id': campaign['campaign_id'],
                'status': 'ENABLED',
                'biddingStrategyConfiguration': {
                    'biddingStrategyType': 'TARGET_CPA',
                    'biddingScheme': {
                        'BiddingScheme.Type': 'TargetCpaBiddingScheme',
                        'TargetCpa': {
                            'ComparableValue.Type': 'Money',
                            'microAmount': 145000000
                        }
                    }
                }
            }
         })

and get error:
Traceback (most recent call last):
  File "/Users/rromio/PycharmProjects/litres/oper.py", line 32, in <module>
    request = campaign_service.mutate(operations)
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1379, in MakeSoapRequest
    packed_args = self._PackArguments(method_name, args)
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1237, in _PackArguments
    for ((_, param), param_data) in zip(op_params, args)]
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1237, in <listcomp>
    for ((_, param), param_data) in zip(op_params, args)]
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1292, in _PackArgumentsHelper
    for item in data]
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1292, in <listcomp>
    for item in data]
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1282, in _PackArgumentsHelper
    elem_type, type_override is not None, data_formatted, set_type_attrs)
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1349, in _CreateComplexTypeFromData
    for k, v in data if k != 'xsi_type'}
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1349, in <dictcomp>
    for k, v in data if k != 'xsi_type'}
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1282, in _PackArgumentsHelper
    elem_type, type_override is not None, data_formatted, set_type_attrs)
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1349, in _CreateComplexTypeFromData
    for k, v in data if k != 'xsi_type'}
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1349, in <dictcomp>
    for k, v in data if k != 'xsi_type'}
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1282, in _PackArgumentsHelper
    elem_type, type_override is not None, data_formatted, set_type_attrs)
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1349, in _CreateComplexTypeFromData
    for k, v in data if k != 'xsi_type'}
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1349, in <dictcomp>
    for k, v in data if k != 'xsi_type'}
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1282, in _PackArgumentsHelper
    elem_type, type_override is not None, data_formatted, set_type_attrs)
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1349, in _CreateComplexTypeFromData
    for k, v in data if k != 'xsi_type'}
  File "/Users/rromio/PycharmProjects/litres/litres_venv/lib/python3.7/site-packages/googleads/common.py", line 1349, in <dictcomp>
    for k, v in data if k != 'xsi_type'}
KeyError: 'TargetCpa'

Google Ads API support replied me:
"The error you are facing is a client library specific issue. You will need to reach out to the owners of the client library by creating an issue so that they can assist you."

All my code:
```
from googleads import adwords

login = '966-689-5905'
list_new_bids = [{'campaign_id': 1838273441, 'bid_micro_amount': 145000000}]

#Отправляем вычисленные ставки
campaign_service = adwords.AdWordsClient.LoadFromStorage(server_path_googleads_yaml).GetService('CampaignService', version='v201809')

operations = []
for campaign in list_new_bids:
    operations.append(
        {'operator': 'SET',
            'operand': {
                'id': campaign['campaign_id'],
                'status': 'ENABLED',
                'biddingStrategyConfiguration': {
                    'biddingStrategyType': 'TARGET_CPA',
                    'biddingScheme': {
                        'BiddingScheme.Type': 'TargetCpaBiddingScheme',
                        'TargetCpa': {
                            'ComparableValue.Type': 'Money',
                            'microAmount': campaign['bid_micro_amount']
                        }
                    }
                }
            }
         })

print(operations)

request = campaign_service.mutate(operations)
```

How can I solve the problem?

**Comment by wihl** [comment]
This issue is related to the legacy [AdWords API](https://github.com/googleads/googleads-python-lib). If this is still a problem specific to Python, either file an issue in that repository or use the [public forums](https://groups.google.com/forum/#!forum/adwords-api).
