### ISSUE TITLE
Service Account error when developer_token not specified

### ISSUE THREAD

**Issue by toddy86** [googleads/google-ads-python#178]
Hi, 

We are using a service account to authenticate with the Google Ads API, however when we attempt to run the example "get_campaigns.py", we get a ValueError that a required field ('developer_token') is required. However, in the example google-ads.yaml file it states that we are to "remove the four Oauth credentials above". 

See the attached screenshot of the google-ads.yaml file and the error generated. 
**google-ads.yaml**
![google-ads-yaml](https://user-images.githubusercontent.com/10559757/66066747-05d5a300-e542-11e9-95a3-373891e1f8f4.png)

**Error**
`Traceback (most recent call last):
  File "ietl/impy/igoogle/ads/ads_api.py", line 8, in <module>
    client = GoogleAdsClient.load_from_storage("/home/tdq/ietl/google-ads.yaml")
  File "/home/tdq/venv/google_ads/lib/python3.6/site-packages/google/ads/google_ads/client.py", line 149, in load_from_storage
    config_data = config.load_from_yaml_file(path)
  File "/home/tdq/venv/google_ads/lib/python3.6/site-packages/google/ads/google_ads/config.py", line 44, in validation_wrapper
    config_dict = func(*args, **kwargs)
  File "/home/tdq/venv/google_ads/lib/python3.6/site-packages/google/ads/google_ads/config.py", line 60, in parser_wrapper
    config_dict = func(*args, **kwargs)
  File "/home/tdq/venv/google_ads/lib/python3.6/site-packages/google/ads/google_ads/config.py", line 130, in load_from_yaml_file
    return parse_yaml_document_to_dict(yaml_doc)
  File "/home/tdq/venv/google_ads/lib/python3.6/site-packages/google/ads/google_ads/config.py", line 45, in validation_wrapper
    validate_dict(config_dict)
  File "/home/tdq/venv/google_ads/lib/python3.6/site-packages/google/ads/google_ads/config.py", line 82, in validate_dict
    str(_REQUIRED_KEYS)))
ValueError: A required field in the configuration data was not found. The required fields are: ('developer_token',)`

Is there an issue here, or an I misinterpreting that the developer_token is part of these 4 OAuth credentials?

Todd

**Comment by toddy86** [comment]
Per https://developers.google.com/google-ads/api/docs/oauth/service-accounts a developer token is required. The details in the google-ads.yaml aren’t overly clear on this fact.

**Comment by toddy86** [comment]
But then on this page https://developers.google.com/google-ads/api/docs/client-libs/python/oauth-service it clear says “ so if you want to use a Service Account authentication make sure credentials for the other flows are not present in your configuration.”. The developer token is nestled under the first option, so does this mean the developer id should or should not be included? 

When it is included, we no longer get the developer token error above, but rather we get a UNAUTHENTICATED exception.
