### ISSUE TITLE
GoogleAdsService returns uniterable _StreamingResponseIterator  

### ISSUE THREAD

**Issue by stijnvanlieshout** [googleads/google-ads-python#271]
I'm following [this example](https://github.com/googleads/google-ads-python/blob/master/examples/reporting/get_keyword_stats.py) on how to query the keyword performance reports using `search_stream`. 

I use the exact query from that example. It fails in the try block:
```
ga_service = client.get_service('GoogleAdsService', version='v3')
response = ga_service.search_stream(customer_id, query)
print(response) 
# print output = <google.api_core.grpc_helpers._StreamingResponseIterator object at 0x10bf6c240>
try:
	for batch in response:
		for row in batch.results:
			campaign = row.campaign
...
```

The try block always fails with the error: `AttributeError: '_SingleThreadedRendezvous' object has no attribute 'add_done_callback'`

I tried calling some of the attributes in this StreamingResponseIterator object without luck:
```
print(response.initial_metadata()) # Prints None
print(response.next()) # Also returns in above _SingleThreadedRendezvous error
```

So the proposed way to iterate over the stream response in your example is not working for me. Any idea why not?

**Comment by wihl** [comment]
Can post your query (without any personal identifiable information)?

**Comment by stijnvanlieshout** [comment]
Hi Wihl. Thanks for looking into this. I've shared the query below. As said, it's a 1-1 copy of [the query you provide](https://github.com/googleads/google-ads-python/blob/master/examples/reporting/get_keyword_stats.py).

```
	ga_service = client.get_service('GoogleAdsService', version='v3')

	# Set fields to retrieve
	query = ('SELECT campaign.id, campaign.name, ad_group.id, ad_group.name, '
                 'ad_group_criterion.criterion_id, '
                 'ad_group_criterion.keyword.text, '
                 'ad_group_criterion.keyword.match_type, '
                 'metrics.impressions, metrics.clicks, metrics.cost_micros '
                 'FROM keyword_view WHERE segments.date DURING LAST_7_DAYS '
                 'AND campaign.advertising_channel_type = \'SEARCH\' '
                 'AND ad_group.status = \'ENABLED\' '
                 'AND ad_group_criterion.status IN (\'ENABLED\', \'PAUSED\') '
                 'ORDER BY metrics.impressions DESC '
                 'LIMIT 50')

	response = ga_service.search_stream(customer_id, query)
```

**Comment by BenRKarl** [comment]
@stijnvanlieshout what version of `google-api-core` do you have installed if you run `pip freeze`?

**Comment by stijnvanlieshout** [comment]
@BenRKarl I was on `1.14.2` of `google-api-core`. I just updated to `1.17.0` but that did not solve the issue. Updating `google-api-python-client` to `1.8.2` also did not help.

**Comment by BenRKarl** [comment]
@stijnvanlieshout which version of Python are you using?

**Comment by stijnvanlieshout** [comment]
I'm on python version `3.7.3`. 

I've included the full stack trace error below. Perhaps you spot something I'm missing here. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/dev/myapp/api/app/sources/routes.py", line 42, in get_report
    result = get_google_performance_report(client, data_dump["credentials"], data_dump["projectTypeId"], data_dump["startDate"], data_dump["endDate"], data_dump["report"], data_dump["options"])
  File "/Users/user/dev/myapp/api/app/sources/google_ads/reports.py", line 35, in get_google_performance_report
    response = ga_service.search_stream(customer_id, query)
  File "/usr/local/lib/python3.7/site-packages/google/ads/google_ads/v3/services/google_ads_service_client.py", line 314, in search_stream
    return self._inner_api_calls['search_stream'](request, retry=retry, timeout=timeout, metadata=metadata)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 144, in error_remapped_callable
    return _StreamingResponseIterator(result)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 72, in __init__
    self._stored_first_result = six.next(self._wrapped)
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 144, in __next__
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 336, in __call__
    continuation, client_call_details, request)
  File "/usr/local/lib/python3.7/site-packages/google/ads/google_ads/interceptors/logging_interceptor.py", line 296, in intercept_unary_stream
    response.add_done_callback(on_rpc_complete)
  File "/usr/local/lib/python3.7/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 73, in add_done_callback
    return self._underlay_call.add_done_callback(fn)
AttributeError: '_SingleThreadedRendezvous' object has no attribute 'add_done_callback'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/dev/myapp/api/app/sources/routes.py", line 42, in get_report
    result = get_google_performance_report(client, data_dump["credentials"], data_dump["projectTypeId"], data_dump["startDate"], data_dump["endDate"], data_dump["report"], data_dump["options"])
  File "/Users/user/dev/myapp/api/app/sources/google_ads/reports.py", line 35, in get_google_performance_report
    response = ga_service.search_stream(customer_id, query)
  File "/usr/local/lib/python3.7/site-packages/google/ads/google_ads/v3/services/google_ads_service_client.py", line 314, in search_stream
    return self._inner_api_calls['search_stream'](request, retry=retry, timeout=timeout, metadata=metadata)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 144, in error_remapped_callable
    return _StreamingResponseIterator(result)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 72, in __init__
    self._stored_first_result = six.next(self._wrapped)
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 144, in __next__
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 336, in __call__
    continuation, client_call_details, request)
  File "/usr/local/lib/python3.7/site-packages/google/ads/google_ads/interceptors/logging_interceptor.py", line 296, in intercept_unary_stream
    response.add_done_callback(on_rpc_complete)
  File "/usr/local/lib/python3.7/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 73, in add_done_callback
    return self._underlay_call.add_done_callback(fn)
AttributeError: '_SingleThreadedRendezvous' object has no attribute 'add_done_callback'
```

**Comment by stijnvanlieshout** [comment]
@BenRKarl I was wondering if you already found the time to look at the additional details I shared? If you need anything else from me please let me know. This bug really stops me from migrating from the Adwords to the Google Ads API.

**Comment by BenRKarl** [comment]
@stijnvanlieshout sorry I'm a bit behind on this one. I haven't yet been able to reproduce this issue for some reason. I'm still working on it though, I'll try to prioritize it this week and get you unblocked.

**Comment by QuinRiva** [comment]
I'm also encountering this issue.
```
google-api-core==1.17.0
google-ads==5.1.0
python version 3.8.3
```

The code I'm running is:
```
client = GoogleAdsClient.load_from_storage('path_to_directory/googleads.yaml')
customer_id = 'OURCUSTOMER_ID'
ga_service = client.get_service('GoogleAdsService', version='v3')

query = ('SELECT campaign.id, campaign.name FROM campaign '
         'ORDER BY campaign.id')

# Issues a search request using streaming.
response = ga_service.search_stream(customer_id, query=query)

try:
    for batch in response:
        for row in batch.results:
            print(f'Campaign with ID {row.campaign.id.value} and name '
                  f'"{row.campaign.name.value}" was found.')
except GoogleAdsException as ex:
    print(f'Request with ID "{ex.request_id}" failed with status '
          f'"{ex.error.code().name}" and includes the following errors:')
    for error in ex.failure.errors:
        print(f'\tError with message "{error.message}".')
        if error.location:
            for field_path_element in error.location.field_path_elements:
                print(f'\t\tOn field: {field_path_element.field_name}')
    sys.exit(1)
```

**Comment by QuinRiva** [comment]
Note that the code will run successfuly if I change it to use `ga_service.search` rather than `ga_service.search_stream` :

```
...
# Issues a search request WITHOUT using streaming.
results = ga_service.search(customer_id, query=query)

try:
#     for batch in response:
    for row in results:
...
```

**Comment by stijnvanlieshout** [comment]
I just checked and just like for @QuinRiva `search` works fine, while `search_stream` does not.

**Comment by BenRKarl** [comment]
@stijnvanlieshout @QuinRiva It looks like an instance of `_SingleThreadedRendezvous` is being passed into the `_UnaryStreamWrapper` class as the `underlay_call` instead of a `_MultiThreadedRendezvous`.  What version of `grpcio` are you both using?

**Comment by stijnvanlieshout** [comment]
@BenRKarl I was on grpcio `1.28.0` and just updated to `1.29.0` but I keep seeing the same error

**Comment by QuinRiva** [comment]
> @stijnvanlieshout @QuinRiva It looks like an instance of `_SingleThreadedRendezvous` is being passed into the `_UnaryStreamWrapper` class as the `underlay_call` instead of a `_MultiThreadedRendezvous`. What version of `grpcio` are you both using?
I'm running 1.29.0.

**Comment by QuinRiva** [comment]
Any update on this?  I have updated to the latest v4 release, along with updating `grpcio` to `1.30.0` and I'm still encountering the same issue.

**Comment by Greg-Asquith** [comment]
This is now a major blocker for me as well, with the same error traces/versions as above

Code was working fine for a while, but it seems installing something has broken the stream response (last changes to overall code base was support for Cloud Storage API as well as Ads)

**Comment by BenRKarl** [comment]
@Greg-Asquith thanks for posting that solution - @QuinRiva @stijnvanlieshout is it a similar problem for you?

**Comment by QuinRiva** [comment]
I'll have to confirm next week, but we use google-cloud-storage in combination with google-ads as part of our data transfer pipeline.  Is there a specific version of cloud-storage that is know to be an issue?

**Comment by BenRKarl** [comment]
@QuinRiva just curious if you were able to fix this issue with the suggestion from @Greg-Asquith. I'm not yet sure if there is a specific version that's incompatible, I'll need to coordinate with the owners of that module to determine the cause and a fix.

**Comment by gmdev** [comment]
I am experiencing the same problem and I don't have `google-cloud-storage` package installed.

What I noticed though is that the `search_stream` queries work fine when executed as a standalone Python script, however they do not work in Flask environment, as part of the app. When running locally, both these methods are using the same virtualenv, so the client libraries versions are the same.

**Comment by BenRKarl** [comment]
@gmdev We do set the single threaded option to true [here](https://github.com/googleads/google-ads-python/blob/master/google/ads/googleads/client.py#L50). Seems the issue may be that other libraries may be changing the single threaded option back to false?

**Comment by BenRKarl** [comment]
Hi all - going to move this to closed for now, but please reopen it if the issue persists.
