### ISSUE TITLE
Google ads API client doesn't work when using pyinstaller 

### ISSUE THREAD

**Issue by aylon11** [googleads/google-ads-python#285]
Im creating a tool to manage UAC assets, utilizing both adwords and google-ads API.

Im now trying to package the tool and have decided that the best way to deliver it was bundling it up as an executable using pyinstaller.

Once i bundle the app, i run the resulted executable and the API calls i make using the adwords API work just fine, but the ones im trying to make using the google-ads API doesn't work.

To be more specific - when trying to create a client using this call:

`ga_service = client.get_service('GoogleAdsService', version='v2')`

i get the following errors:

```
Traceback (most recent call last):
  File "google/ads/google_ads/client.py", line 72, in _get_api_services_by_version
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'google.ads.google_ads.v2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 2284, in wsgi_app
  File "flask/app.py", line 1807, in full_dispatch_request
  File "flask/app.py", line 1710, in handle_user_exception
  File "flask/_compat.py", line 35, in reraise
  File "flask/app.py", line 1805, in full_dispatch_request
  File "flask/app.py", line 1791, in dispatch_request
  File "assetMG.py", line 73, in get_all_accounts_assets
    return get_specific_accounts_assets(cid)
  File "assetMG.py", line 86, in get_specific_accounts_assets
    res = get_accounts_assets(googleads_client, cid)
  File "app/backend/get_all_assets.py", line 33, in get_accounts_assets
    ga_service = client.get_service('GoogleAdsService', version=version)
  File "google/ads/google_ads/client.py", line 216, in get_service
  File "google/ads/google_ads/client.py", line 76, in _get_api_services_by_version
ValueError: Specified Google Ads API version "v2" does not exist. Valid API versions are: "v2", "v1"
```

What I believe happens, is that since i "freeze" the app using pyinstller, the google-ads client library is not able to dynamically import the module according to the version i specified during runtime. As seen in this function:

```
    @classmethod
    def _get_api_services_by_version(cls, version):
        """Returns a module with all services and types for a given API version.

        Args:
            version: a str indicating the API version.

        Returns:
            A module containing all services and types for the a API version.
        """
        try:
            version_module = import_module('google.ads.google_ads.%s' % version)
        except ImportError:
            raise ValueError('Specified Google Ads API version "{}" does not '
                             'exist. Valid API versions are: "{}"'.format(
                                 version, '", "'.join(_VALID_API_VERSIONS)))
        return version_module
```

Can you please advise? Any ideas on how to workaround that?

Thanks,
Eylon

**Comment by wihl** [comment]
You are likely seeing this because we implemented lazy loading to improve performance. See https://github.com/googleads/google-ads-python/issues/197. I don't have a lot of experience with pyinstaller, but if you can implement lazy loading when building your package, it should resolve the issue.
