### ISSUE TITLE
Specified service does not exist in Google Ads API v5. error

### ISSUE THREAD

**Issue by sidhart** [googleads/google-ads-python#330]
Hi,
Getting error below when I try to initiate any service as below. Could you please advise what needs to be changed? 

client = GoogleAdsClient.load_from_storage("googleads.yaml")
keyword_plan_idea_service = client.get_service("KeywordPlanIdeaService")

*** print_exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\ads\google_ads\client.py", line 252, in get_service
    api_module, _SERVICE_CLIENT_TEMPLATE.format(name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\ads\google_ads\v5\__init__.py", line 272, in __getattr__
    module = __getattr__(util.convert_upper_case_to_snake_case(name))
AttributeError: module 'google.api_core' has no attribute 'gapic_v1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\Search insights\Google Adwords API\Code\get_related_keywords.py", line 16, in <module>
    keyword_plan_idea_service = client.get_service("KeywordPlanIdeaService")
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\ads\google_ads\client.py", line 257, in get_service
    "Ads API {}.".format(name, version)
ValueError: Specified service KeywordPlanIdeaService" does not exist in Google Ads API v5.

Running Python 3.7.3
packages installed:
google-ads==7.0.0
google-api-core==1.23.0
google-api-python-client==1.12.5
google-auth==1.22.1
google-auth-httplib2==0.0.4
google-auth-oauthlib==0.4.1
googleads==25.0.0
googleapis-common-protos==1.52.0

**Comment by BenRKarl** [comment]
@sidhart this shouldn't be an issue in the latest release, `10.0.0`
