### ISSUE TITLE
Internal error when labels in WHERE but not in SELECT

### ISSUE THREAD

**Issue by estevopaz** [googleads/google-ads-python#339]
This query works fine:
```sql
SELECT campaign.id, campaign.labels
FROM campaign
WHERE campaign.labels CONTAINS ANY (...)
```
But if you remove campaign.labels from SELECT, it provokes an internal error.
Same bug with ad_group.labels

No relevant issue, but it provokes a waste of time on the API integration.

**Comment by BenRKarl** [comment]
Can you share the full request/response logs, redacting any sensitive tokens?

**Comment by estevopaz** [comment]
With campaign.labels in SELECT, it works as expected, just removing it:
```
2020-11-20 08:56:40.947 : DEBUG : hoot.adwords.query : 3294 : AWQL: SELECT label.name, label.resource_name FROM label
2020-11-20 08:56:40.948 : DEBUG : google.auth.transport.requests : Making request: POST https://accounts.google.com/o/oauth2/token
2020-11-20 08:56:42.426 : DEBUG : google.auth.transport.requests : Making request: POST https://accounts.google.com/o/oauth2/token
2020-11-20 08:56:42.947 : DEBUG : hoot.adwords.query : 3294 : AWQL: 
        SELECT campaign.id, campaign.name
        FROM campaign
        WHERE campaign.status = ENABLED
          AND campaign.name NOT LIKE '%[!]%'
          AND campaign.advertising_channel_type = SEARCH
          AND campaign.labels CONTAINS ANY ('customers/5542127990/labels/4209741088')
    
2020-11-20 08:56:43.244 : WARNING : google.ads.google_ads.client : Request made: ClientCustomerId: 5542127990, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v6.services.GoogleAdsService/SearchStream, RequestId: i4CiZS9-1JikZlpVdc5Vfw, IsFault: True, FaultMessage: Internal error encountered.
Traceback (most recent call last):
  File "/home/estevo/.local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 150, in error_remapped_callable
    return _StreamingResponseIterator(result, prefetch_first_result=prefetch_first)
  File "/home/estevo/.local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 73, in __init__
    self._stored_first_result = six.next(self._wrapped)
  File "/home/estevo/.local/lib/python3.8/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 100, in __next__
    raise e
  File "/home/estevo/.local/lib/python3.8/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 97, in __next__
    self._failure_handler(self._underlay_call)
  File "/home/estevo/.local/lib/python3.8/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 141, in _handle_grpc_failure
    raise self._get_error_from_response(response)
  File "/home/estevo/.local/lib/python3.8/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 92, in __next__
    return next(self._underlay_call)
  File "/home/estevo/.local/lib/python3.8/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/home/estevo/.local/lib/python3.8/site-packages/grpc/_channel.py", line 620, in _next
    return self._next_response()
  File "/home/estevo/.local/lib/python3.8/site-packages/grpc/_channel.py", line 607, in _next_response
    raise self
grpc._channel._SingleThreadedRendezvous: <_SingleThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Internal error encountered."
	debug_error_string = "{"created":"@1605862603.244355607","description":"Error received from peer ipv4:216.58.209.74:443","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Internal error encountered.","grpc_status":13}"
```

**Comment by BenRKarl** [comment]
@estevopaz I'm not currently able to reproduce this myself, are you still seeing these errors?

**Comment by BenRKarl** [comment]
Closing this issue as it's gone stale, but please reopen if this issue persists.
