### ISSUE TITLE
Segfault in grpc when using search_stream

### ISSUE THREAD

**Issue by BenRKarl** [googleads/google-ads-python#384]
Transfer of [this Issue](https://github.com/googleads/googleads-python-lib/issues/479) to the correct library.

**Comment by baecher** [comment]
I believe I am running into the same issue as OP.

Query I am running:
```
SELECT customer.id FROM customer_client
```

Result when using `search_stream()`
```
E0222 21:23:47.149911263   23046 metadata.cc:253]            WARNING: 1 metadata elements were leaked
E0222 21:23:47.149972595   23046 metadata.cc:260]            mdelem 'user-agent' = 'grpc-python/1.35.0 grpc-c/14.0.0 (linux; chttp2)'
E0222 21:23:47.150003341   23046 metadata.cc:253]            WARNING: 1 metadata elements were leaked
E0222 21:23:47.150068236   23046 metadata.cc:260]            mdelem 'content-disposition' = 'attachment'
E0222 21:23:47.150107762   23046 metadata.cc:253]            WARNING: 1 metadata elements were leaked
E0222 21:23:47.150131452   23046 metadata.cc:260]            mdelem 'alt-svc' = 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"'
E0222 21:23:47.150158564   23046 metadata.cc:253]            WARNING: 1 metadata elements were leaked
E0222 21:23:47.150177433   23046 metadata.cc:260]            mdelem 'request-id' = 'lporU0bHJohOjAQUMseoNg'
E0222 21:23:47.150195790   23046 metadata.cc:253]            WARNING: 1 metadata elements were leaked
E0222 21:23:47.150214088   23046 metadata.cc:260]            mdelem ':authority' = 'googleads.googleapis.com:443'
[mutex.cc : 424] RAW: Lock blocking 0x2a4dea0   @
[mutex.cc : 424] RAW: Lock returning 0x2a4dea0   @
double free or corruption (fasttop)
Aborted (core dumped)
```

It is noteworthy that the non-stream search call works as expected.

```
$ pip freeze
cachetools==4.2.1
certifi==2020.12.5
chardet==4.0.0
google-ads==9.0.0
google-api-core==1.26.0
google-auth==1.27.0
google-auth-oauthlib==0.4.2
googleapis-common-protos==1.52.0
grpcio==1.35.0
idna==2.10
oauthlib==3.1.0
packaging==20.9
pep562==1.0
protobuf==3.15.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.1
six==1.15.0
urllib3==1.26.3
```

**Comment by BenRKarl** [comment]
@baecher do you get different results if you revert your version of `grpcio` back to 1.33.1 or 1.34.0?

**Comment by baecher** [comment]
1.34.0 exhibits the same behavior:

```
E0222 21:52:36.994776733   24307 metadata.cc:253]            WARNING: 1 metadata elements were leaked
E0222 21:52:36.994828949   24307 metadata.cc:260]            mdelem 'alt-svc' = 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"'
E0222 21:52:36.994856312   24307 metadata.cc:253]            WARNING: 2 metadata elements were leaked
E0222 21:52:36.994876103   24307 metadata.cc:260]            mdelem ':authority' = 'googleads.googleapis.com:443'
E0222 21:52:36.994908142   24307 metadata.cc:260]            mdelem 'request-id' = 'wtCmPuNEasWzdoh1J1NADA'
E0222 21:52:36.994927517   24307 metadata.cc:253]            WARNING: 1 metadata elements were leaked
E0222 21:52:36.994961696   24307 metadata.cc:260]            mdelem 'user-agent' = 'grpc-python/1.34.0 grpc-c/14.0.0 (linux; chttp2)'
E0222 21:52:36.994984940   24307 metadata.cc:253]            WARNING: 1 metadata elements were leaked
E0222 21:52:36.995019650   24307 metadata.cc:260]            mdelem 'content-disposition' = 'attachment'
double free or corruption (fasttop)
Aborted (core dumped)
```

1.33.2 shows something different, but this is actually non-deterministic - a second run showed the same as above:
```
E0222 21:58:38.949971050   24544 metadata.cc:253]            WARNING: 1 metadata elements were leaked
E0222 21:58:38.950028092   24544 metadata.cc:260]            mdelem ':authority' = 'googleads.googleapis.com:443'
E0222 21:58:38.950041783   24544 metadata.cc:253]            WARNING: 2 metadata elements were leaked
E0222 21:58:38.950051325   24544 metadata.cc:260]            mdelem 'content-disposition' = 'attachment'
E0222 21:58:38.950060537   24544 metadata.cc:260]            mdelem 'request-id' = 'hUtBMuX3IaCJOocII9QKEg'
E0222 21:58:38.950090386   24544 metadata.cc:253]            WARNING: 1 metadata elements were leaked
E0222 21:58:38.950114672   24544 metadata.cc:260]            mdelem 'alt-svc' = 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"'
E0222 21:58:38.950148530   24544 metadata.cc:253]            WARNING: 1 metadata elements were leaked
E0222 21:58:38.950170987   24544 metadata.cc:260]            mdelem 'user-agent' = 'grpc-python/1.33.2 grpc-c/13.0.0 (linux; chttp2)'
[mutex.cc : 422] RAW: Lock blocking 0x2a64360   @
[mutex.cc : 1895] RAW: Check (v & (kMuWait | kMuWrWait)) != kMuWrWait failed: Lock: Mutex corrupt: waiting writer with no waiters: 0x2a23ff0
Aborted (core dumped)
```

1.33.1 has unmet dependencies:
```
google-ads 9.0.0 requires grpcio<2.0.0,>=1.33.2, but you have grpcio 1.33.1 which is incompatible.
```
```
Traceback (most recent call last):
  File "a/bin/sem-emergency-stop", line 8, in <module>
    sys.exit(run())
  File "/tmp/a/lib/python3.8/site-packages/ses/main.py", line 349, in run
    args.func(client, args)
  File "/tmp/a/lib/python3.8/site-packages/ses/main.py", line 254, in pause
    return pause_unpause(client, args, True)
  File "/tmp/a/lib/python3.8/site-packages/ses/main.py", line 231, in pause_unpause
    campaign_sets = args.campaign_sets or collect(client, args)
  File "/tmp/a/lib/python3.8/site-packages/ses/main.py", line 210, in collect
    customer_ids = collect_customer_ids(client)
  File "/tmp/a/lib/python3.8/site-packages/ses/main.py", line 45, in collect_customer_ids
    for response in query(
  File "/tmp/a/lib/python3.8/site-packages/ses/main.py", line 37, in query
    return client.get_service('GoogleAdsService', version='v6').search_stream(
  File "/tmp/a/lib/python3.8/site-packages/google/ads/google_ads/v6/services/google_ads_service_client.py", line 366, in search_stream
    return self._inner_api_calls['search_stream'](request, retry=retry, timeout=timeout, metadata=metadata)
  File "/tmp/a/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/tmp/a/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/tmp/a/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/tmp/a/lib/python3.8/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/tmp/a/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 166, in error_remapped_callable
    return _StreamingResponseIterator(result, prefetch_first_result=prefetch_first)
  File "/tmp/a/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 89, in __init__
    self._stored_first_result = six.next(self._wrapped)
  File "/tmp/a/lib/python3.8/site-packages/grpc/_interceptor.py", line 144, in __next__
    raise self._exception
  File "/tmp/a/lib/python3.8/site-packages/grpc/_interceptor.py", line 335, in __call__
    return self._interceptor.intercept_unary_stream(
  File "/tmp/a/lib/python3.8/site-packages/google/ads/google_ads/interceptors/logging_interceptor.py", line 387, in intercept_unary_stream
    response.add_done_callback(on_rpc_complete)
  File "/tmp/a/lib/python3.8/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 73, in add_done_callback
    return self._underlay_call.add_done_callback(fn)
AttributeError: '_SingleThreadedRendezvous' object has no attribute 'add_done_callback'
```

**Comment by ralsina** [comment]
I have tried the version changes like @baecher did and got the same results in my tests Also google-ads 8.0 or 9.0 fail the same way.

**Comment by BenRKarl** [comment]
Thanks @baecher @ralsina I'm not able to reproduce this error yet. Can I ask if you get different results by reverting your version of `protobuf` back to 3.13 or 3.14?

**Comment by baecher** [comment]
@BenRKarl I think I found reliable steps to reproduce and isolated the issue. It appears to be related to something going out of scope that shouldn't.

I've made [these changes](https://gist.github.com/baecher/e2b95ae26912f86115f9112d135c2e74) to the `get_campaign.py` example that should expose the problem. You'll have to run it on an account with a good number of campaigns as the first(?) stream chunk gets processed just fine - I'm testing this with an account with 552 campaigns.

If this still doesn't reproduce, here are some steps that should work 100%:

```
docker run -it --rm python /bin/sh
pip install google-ads
cat > /root/google-ads.yaml
<PASTE CREDENTIALS, CTRL+D>
wget https://gist.githubusercontent.com/baecher/e2b95ae26912f86115f9112d135c2e74/raw/ae4b3986014cffbec414a3cdb00eefed0cbd06de/get_campaigns_buggy.py
python get_campaigns_buggy.py -c CUSTOMER_ID
```

**Comment by baecher** [comment]
Just to state the implicit @ralsina, this can be avoided by having the service object in scope until the stream is exhausted. I believe this is also the root cause for #366 and #369.

**Comment by ralsina** [comment]
Interesting @baecher ! Too bad, that wrapper sure made calls look nicer!

**Comment by ralsina** [comment]
One easy way to do that sort of wrapper and not get the segfault is just to add a reference to the service in the response object to keep the GC happy:

```python
    def search_stream(self, query):
        _service = self._client.get_service("GoogleAdsService", version=self.API_VERSION)
        response = _service.search_stream(self.adwords_account_id, query)
        response.service_reference = _service
        return response

```

**Comment by henribru** [comment]
Not sure if it's the same issue but I was also getting segfaults using `search_stream` and setting the environment variable `GRPC_ENABLE_FORK_SUPPORT=1` fixed it

**Comment by BenRKarl** [comment]
@baecher with your diff I think I'm able to reproduce this, is this the same Python error you get?:

```Traceback (most recent call last):
  File "~/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 97, in next
    return six.next(self._wrapped)
  File "~/google-ads-python/google/ads/google_ads/interceptors/exception_interceptor.py", line 100, in __next__
    raise e
  File "~/google-ads-python/google/ads/google_ads/interceptors/exception_interceptor.py", line 97, in __next__
    self._failure_handler(self._underlay_call)
  File "~/google-ads-python/google/ads/google_ads/interceptors/exception_interceptor.py", line 141, in _handle_grpc_failure
    raise self._get_error_from_response(response)
  File "~/google-ads-python/google/ads/google_ads/interceptors/exception_interceptor.py", line 92, in __next__
    return next(self._underlay_call)
  File "~/lib/python3.7/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "~/lib/python3.7/site-packages/grpc/_channel.py", line 620, in _next
    return self._next_response()
  File "~/lib/python3.7/site-packages/grpc/_channel.py", line 607, in _next_response
    raise self
grpc._channel._SingleThreadedRendezvous: <_SingleThreadedRendezvous of RPC that terminated with:
	status = StatusCode.CANCELLED
	details = "Channel deallocated!"
	debug_error_string = "{"created":"@1614957425.180322022","description":"Error received from peer ipv6:[2607:f8b0:4006:819::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Channel deallocated!","grpc_status":1}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/basic_operations/get_campaigns.py", line 79, in <module>
    main(google_ads_client, args.customer_id)
  File "examples/basic_operations/get_campaigns.py", line 42, in main
    for batch in response:
  File ~lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 100, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.Cancelled: 499 Channel deallocated!
```

**Comment by BenRKarl** [comment]
I was able to get a little more context on the above Python error, though I'm not sure it's connected to the segfault reported above.

Turns out that it's expected behavior for the Channel to be closed if the `grpc.Client` is in a different function scope than the iterator. Some background as to why can be found [here](https://github.com/grpc/grpc/issues/19235). 

So for now I would suggest always keeping the client and the iterator in the same function as a best practice.

Can anyone on this thread confirm whether they experience a segfault when both objects share a scope?

**Comment by BenRKarl** [comment]
Since we've landed on this being a known issue resulting from the grpc client and streaming iterator being used in different function scopes I'm going to close this out, however I've added a feature request for us to document this problem in our documentation set [here](https://developers.google.com/google-ads/api/docs/client-libs/python).
