### ISSUE TITLE
'serialized_options' not found in google\protobuf\descriptor.py

### ISSUE THREAD

**Issue by dglonsdale** [googleads/google-ads-python#40]
Running the get_campaign.py example, using Python 3.6.6 and google-ads 0.7.0.

Full stack trace:

Traceback (most recent call last):
  File "C:\Users\david\Red Apple Services\Admin\Processes and Templates\Python Scripts - Live\get_campaign.py", line 25, in <module>
    import google.ads.google_ads.client
  File "C:\Users\david\AppData\Roaming\Python\Python36\site-packages\google\ads\google_ads\__init__.py", line 19, in <module>
    import google.ads.google_ads.client
  File "C:\Users\david\AppData\Roaming\Python\Python36\site-packages\google\ads\google_ads\client.py", line 27, in <module>
    from google.ads.google_ads.v0.proto.errors import errors_pb2 as error_protos
  File "C:\Users\david\AppData\Roaming\Python\Python36\site-packages\google\ads\google_ads\v0\__init__.py", line 19, in <module>
    from google.ads.google_ads.v0 import types
  File "C:\Users\david\AppData\Roaming\Python\Python36\site-packages\google\ads\google_ads\v0\types.py", line 22, in <module>
    from google.ads.google_ads.v0.proto.common import ad_type_infos_pb2
  File "C:\Users\david\AppData\Roaming\Python\Python36\site-packages\google\ads\google_ads\v0\proto\common\ad_type_infos_pb2.py", line 15, in <module>
    from google.ads.google_ads.v0.proto.enums import call_conversion_reporting_state_pb2 as google_dot_ads_dot_googleads__v0_dot_proto_dot_enums_dot_call__conversion__reporting__state__pb2
  File "C:\Users\david\AppData\Roaming\Python\Python36\site-packages\google\ads\google_ads\v0\proto\enums\call_conversion_reporting_state_pb2.py", line 22, in <module>
    serialized_pb=_b('\nIgoogle/ads/googleads_v0/proto/enums/call_conversion_reporting_state.proto\x12\x1dgoogle.ads.googleads.v0.enums\"\xcc\x01\n CallConversionReportingStateEnum\"\xa7\x01\n\x1c\x43\x61llConversionReportingState\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x0c\n\x08\x44ISABLED\x10\x02\x12,\n(USE_ACCOUNT_LEVEL_CALL_CONVERSION_ACTION\x10\x03\x12-\n)USE_RESOURCE_LEVEL_CALL_CONVERSION_ACTION\x10\x04\x42\xf6\x01\n!com.google.ads.googleads.v0.enumsB!CallConversionReportingStateProtoP\x01ZBgoogle.golang.org/genproto/googleapis/ads/googleads/v0/enums;enums\xa2\x02\x03GAA\xaa\x02\x1dGoogle.Ads.GoogleAds.V0.Enums\xca\x02\x1dGoogle\\Ads\\GoogleAds\\V0\\Enums\xea\x02!Google::Ads::GoogleAds::V0::Enumsb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'

**Comment by BenRKarl** [comment]
Hi @dglonsdale thanks for bringing this up. Are you running the example as-is or a modified version of it?

**Comment by dglonsdale** [comment]
I'm running it "as is"; however, the version of Python I'm running is the
ActivePython version, which might not have been updated with all Google's
changes!


David Lonsdale

david@redappleservices.co.uk

t. (+44) 1778 343130

Red Apple Services Ltd., 73 Riverside, Deeping Gate, Peterborough,
Cambridgeshire, PE6 9AR, UK

**Comment by BenRKarl** [comment]
Ok thanks @dglonsdale! I'll look into it and see what I can find out.

P.S. I think your contact info got posted in your last comment so I edited it to remove it.

**Comment by BenRKarl** [comment]
Hi @dglonsdale I'm curious if you're continuing to have this issue in `v1` of the library?

**Comment by dglonsdale** [comment]
To be honest, I haven't retried it, and probably won't take the Python route.
