### ISSUE TITLE
Unable to query custom dates

### ISSUE THREAD

**Issue by maxcountryman** [googleads/google-ads-python#410]
I'm trying to write a query which will query campaigns by a given date range. I'm able to get this to work as expected if I use one of the builtin report ranges, like `LAST_7_DAYS` however when I attempt to use a [custom range](https://developers.google.com/adwords/api/docs/guides/reporting#custom_date_ranges) I get a message like this:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/max/Projects/caravan/adwords.py", line 66, in <module>
    main(google_ads_client)
  File "/Users/max/Projects/caravan/adwords.py", line 35, in main
    response = ga_service.search_stream("[redacted]", query=query)
  File "/Users/max/Projects/caravan/.venv/lib/python3.9/site-packages/google/ads/google_ads/v6/services/google_ads_service_client.py", line 366, in search_stream
    return self._inner_api_calls['search_stream'](request, retry=retry, timeout=timeout, metadata=metadata)
  File "/Users/max/Projects/caravan/.venv/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/max/Projects/caravan/.venv/lib/python3.9/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/Users/max/Projects/caravan/.venv/lib/python3.9/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/max/Projects/caravan/.venv/lib/python3.9/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/Users/max/Projects/caravan/.venv/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 166, in error_remapped_callable
    return _StreamingResponseIterator(result, prefetch_first_result=prefetch_first)
  File "/Users/max/Projects/caravan/.venv/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 89, in __init__
    self._stored_first_result = six.next(self._wrapped)
  File "/Users/max/Projects/caravan/.venv/lib/python3.9/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 100, in __next__
    raise e
  File "/Users/max/Projects/caravan/.venv/lib/python3.9/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 97, in __next__
    self._failure_handler(self._underlay_call)
  File "/Users/max/Projects/caravan/.venv/lib/python3.9/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 141, in _handle_grpc_failure
    raise self._get_error_from_response(response)
google.ads.google_ads.errors.GoogleAdsException: (<_SingleThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Request contains an invalid argument."
        debug_error_string = "{"created":"@1619037402.855953000","description":"Error received from peer ipv4:74.125.202.95:443","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Request contains an invalid argument.","grpc_status":3}"
>, <_SingleThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Request contains an invalid argument."
        debug_error_string = "{"created":"@1619037402.855953000","description":"Error received from peer ipv4:74.125.202.95:443","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Request contains an invalid argument.","grpc_status":3}"
>, errors {
  error_code {
    query_error: BAD_VALUE
  }
  message: "Error in WHERE clause: invalid value 20210101."
}
, 'n-EONS_BZialb1_cd3pFbg')
```

Where my query looks like this:

```python

    query = """
    select
      campaign.id,
      campaign.name,
      campaign.status,
      metrics.impressions,
      metrics.clicks,
      metrics.cost_micros,
      segments.date
    from
      campaign
    where
      segments.date during 20210101,20210102
    order by
      campaign.id
    """
```

**Comment by BenRKarl** [comment]
@maxcountryman that documentation you linked to is for the old XML-based AdWords API, the new syntax is documented [here](https://developers.google.com/google-ads/api/docs/query/grammar).

You should be able to get the results you want with `between`

`where segments.date between 20210101 and 20210102`
