### ISSUE TITLE
Syntax error when call service

### ISSUE THREAD

**Issue by NikolaKikovski** [googleads/google-ads-python#44]
```Traceback (most recent call last):
  File "/home/nikolai/projects/google-ads-adapter/sdfdsdf.py", line 16, in <module>
    print list(campaigns)
  File "/home/nikolai/projects/google-ads-adapter/google_adapter/adapter/services/campaign.py", line 32, in get
    service = self._client.get_service('GoogleAdsService', version='v1')
  File "/home/nikolai/.virtualenvs/google-ads-adapter-qiVpOMiY/local/lib/python2.7/site-packages/google/ads/google_ads/client.py", line 189, in get_service
    api_module = _get_version(version)
  File "/home/nikolai/.virtualenvs/google-ads-adapter-qiVpOMiY/local/lib/python2.7/site-packages/google/ads/google_ads/client.py", line 681, in _get_version
    version = import_module('google.ads.google_ads.%s' % name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/nikolai/.virtualenvs/google-ads-adapter-qiVpOMiY/local/lib/python2.7/site-packages/google/ads/google_ads/v1/__init__.py", line 19
    from google.ads.google_ads.1 import types
                               ^
SyntaxError: invalid syntax```

**Comment by NikolaKikovski** [comment]
is it bug only on my side?

**Comment by NikolaKikovski** [comment]
Sorry! I did not immediately notice this pull request https://github.com/googleads/google-ads-python/pull/43
