### ISSUE TITLE
ValueError: Specified Google Ads API version "v1" does not exist.

### ISSUE THREAD

**Issue by ReptilianBrain** [googleads/google-ads-python#45]
Good morning

When running the get_campaigns.py from the basic example folder we get to following error

`Traceback (most recent call last):
  File "/Users/cgagnon/Documents/projects/gads-beta/.venv/lib/python3.7/site-packages/google/ads/google_ads/client.py", line 334, in _get_version
    version = getattr(google.ads.google_ads, name)
AttributeError: module 'google.ads.google_ads' has no attribute 'v1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/Documents/projects/gads-beta/google-ads-python/examples/basic_operations/get_campaigns.py", line 67, in <module>
    main(google_ads_client, args.customer_id, _DEFAULT_PAGE_SIZE)
  File "/Users/user/Documents/projects/gads-beta/google-ads-python/examples/basic_operations/get_campaigns.py", line 32, in main
    ga_service = client.get_service('GoogleAdsService', version='v1')
  File "/Users/user/Documents/projects/gads-beta/.venv/lib/python3.7/site-packages/google/ads/google_ads/client.py", line 173, in get_service
    version = _get_version(version)
  File "/Users/user/Documents/projects/gads-beta/.venv/lib/python3.7/site-packages/google/ads/google_ads/client.py", line 337, in _get_version
    % name)
ValueError: Specified Google Ads API version "v1" does not exist.`

**Comment by BenRKarl** [comment]
Hi @ReptilianBrain - thanks for creating this issue. There was a small bug in the last release and there's a [PR](https://github.com/googleads/google-ads-python/pull/43) to fix it here. I expect this will be released today. Thanks for your patience, and apologies for the inconvenience!

**Comment by BenRKarl** [comment]
Hi @ReptilianBrain - version 1.0.1 of this library has been published with a fix for this bug. Thanks for reporting it! And once again apologies for the inconvenience.
