### ISSUE TITLE
ValueError: Specified type 'DismissRecommendationOperation' does not exist in Google Ads API v10

### ISSUE THREAD

**Issue by brightbid-edmund** [googleads/google-ads-python#596]
**Describe the bug:**
I am getting the following runtime error. Also the dismiss recommendation example has an error.

```
Traceback (most recent call last):
  File "/Users/edmund/projects/brightbid/brightbid/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edmund/projects/brightbid/brightbid/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/edmund/projects/brightbid/brightbid/venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/edmund/projects/brightbid/brightbid/apps/portal/views.py", line 129, in customer_detail
    dismiss_all_recommendations(customer)
  File "/Users/edmund/projects/brightbid/brightbid/apps/api/services/google/recommendations.py", line 141, in dismiss_all_recommendations
    dismiss_recommendation_operation = client.get_type(
  File "/Users/edmund/projects/brightbid/brightbid/venv/lib/python3.9/site-packages/google/ads/googleads/client.py", line 443, in get_type
    raise ValueError(
ValueError: Specified type 'DismissRecommendationOperation' does not exist in Google Ads API v10
```

**Steps to Reproduce:**

```
        recommendation_service = client.get_service("RecommendationService")
        dismiss_recommendation_operation = client.get_type(
            "DismissRecommendationOperation"
        )
```

**Expected behavior:**

No error. this is the only operation that does not work

**Client library version and API version:**
Client library version:
Google Ads API version:

```
argcomplete==1.12.3
arrow==1.2.1
asgiref==3.4.1
backports.entry-points-selectable==1.1.1
binaryornot==0.4.4
black==21.12b0
cachetools==4.2.4
certifi==2021.10.8
chardet==4.0.0
charset-normalizer==2.0.9
click==8.0.3
colorlog==6.6.0
cookiecutter==1.7.3
Deprecated==1.2.13
distlib==0.3.3
dj-database-url==0.5.0
Django==3.2.10
django-browser-reload==1.3.0
django-environ==0.8.1
django-filter==21.1
django-ninja==0.16.1
django-tailwind==3.1.1
filelock==3.4.0
google-ads==15.0.0
google-api-core==2.7.0
google-auth==2.6.0
google-auth-oauthlib==0.5.0
googleapis-common-protos==1.55.0
grpcio==1.44.0
huey==2.4.3
idna==3.3
importlib-metadata==4.10.1
Jinja2==3.0.3
jinja2-time==0.2.0
jsonfield==3.1.0
Markdown==3.3.6
MarkupSafe==2.0.1
mypy-extensions==0.4.3
nox==2021.10.1
numpy==1.21.5
oauthlib==3.1.1
packaging==21.3
pathspec==0.9.0
platformdirs==2.4.0
poyo==0.5.0
proto-plus==1.18.1
protobuf==3.17.3
psycopg2==2.9.2
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydantic==1.8.2
pyparsing==3.0.6
python-dateutil==2.8.2
python-slugify==5.0.2
pytz==2021.3
PyYAML==5.4.1
redis==4.1.4
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.8
six==1.16.0
sqlparse==0.4.2
text-unidecode==1.3
tomli==1.2.3
typing_extensions==4.0.1
urllib3==1.26.7
virtualenv==20.10.0
whitenoise==5.3.0
wrapt==1.13.3
zipp==3.7.0
```

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**
Mac M1

**Comment by BenRKarl** [comment]
Thanks for pointing this out - it seems like this type is attached to the `DismissRecommendationRequest` type, so to access it you can do:

```
request = client.get_type("DismissRecommendationRequest")
operation = request.DismissRecommendationOperation
```

I'll file a bug for us to update the example.

**Comment by ebchambers** [comment]
I tried this solution and it didn't work.
```
request = client.get_type("DismissRecommendationRequest")
operation = request.DismissRecommendationOperation
```
It gave me this error:
```
AttributeError: DismissRecommendationOperation
```

**Comment by BenRKarl** [comment]
@ebchambers are you by change using `use_proto_plus = False`? The approach is slightly different if so, you would need to do:

```py
request = client.get_type("DismissRecommendationRequest")
operation = request.operations.add()
```

The other logic mentioned should work fine if `use_proto_plus` is set to `True`.

**Comment by ebchambers** [comment]
@BenRKarl Thank you so much! That worked perfectly.
