### ISSUE TITLE
Received message larger than max

### ISSUE THREAD

**Issue by Kremzon** [googleads/google-ads-python#648]
**Describe the bug:**
When trying to query all fields for all ad group ads the client dies in the middle of streaming the data because of a size issue

**Steps to Reproduce:**
```
from google.ads.googleads.client import GoogleAdsClient
from google.protobuf import json_format

data = []
client = GoogleAdsClient.load_from_storage("")
googleads_service = client.get_service("GoogleAdsService")
customerId = ""
query = """
    SELECT ad_group_ad.action_items,ad_group_ad.ad.added_by_google_ads,ad_group_ad.ad.app_ad.descriptions,
           ad_group_ad.ad.app_ad.headlines,ad_group_ad.ad.app_ad.html5_media_bundles,ad_group_ad.ad.app_ad.images,
           ad_group_ad.ad.app_ad.mandatory_ad_text,ad_group_ad.ad.app_ad.youtube_videos,
           ad_group_ad.ad.app_engagement_ad.descriptions,ad_group_ad.ad.app_engagement_ad.headlines,
           ad_group_ad.ad.app_engagement_ad.images,ad_group_ad.ad.app_engagement_ad.videos,
           ad_group_ad.ad.app_pre_registration_ad.descriptions,ad_group_ad.ad.app_pre_registration_ad.headlines,
           ad_group_ad.ad.app_pre_registration_ad.images,ad_group_ad.ad.app_pre_registration_ad.youtube_videos,
           ad_group_ad.ad.call_ad.business_name,ad_group_ad.ad.call_ad.call_tracked,
           ad_group_ad.ad.call_ad.conversion_action,ad_group_ad.ad.call_ad.conversion_reporting_state,
           ad_group_ad.ad.call_ad.country_code,ad_group_ad.ad.call_ad.description1,ad_group_ad.ad.call_ad.description2,
           ad_group_ad.ad.call_ad.disable_call_conversion,ad_group_ad.ad.call_ad.headline1,
           ad_group_ad.ad.call_ad.headline2,ad_group_ad.ad.call_ad.path1,ad_group_ad.ad.call_ad.path2,
           ad_group_ad.ad.call_ad.phone_number,ad_group_ad.ad.call_ad.phone_number_verification_url,
           ad_group_ad.ad.device_preference,ad_group_ad.ad.discovery_carousel_ad.business_name,
           ad_group_ad.ad.discovery_carousel_ad.call_to_action_text,ad_group_ad.ad.discovery_carousel_ad.carousel_cards,
           ad_group_ad.ad.discovery_carousel_ad.description,ad_group_ad.ad.discovery_carousel_ad.headline,
           ad_group_ad.ad.discovery_carousel_ad.logo_image,ad_group_ad.ad.discovery_multi_asset_ad.business_name,
           ad_group_ad.ad.discovery_multi_asset_ad.call_to_action_text,
           ad_group_ad.ad.discovery_multi_asset_ad.descriptions,ad_group_ad.ad.discovery_multi_asset_ad.headlines,
           ad_group_ad.ad.discovery_multi_asset_ad.lead_form_only,ad_group_ad.ad.discovery_multi_asset_ad.logo_images,
           ad_group_ad.ad.discovery_multi_asset_ad.marketing_images,
           ad_group_ad.ad.discovery_multi_asset_ad.portrait_marketing_images,ad_group_ad.ad.discovery_multi_asset_ad.square_marketing_images,
           ad_group_ad.ad.display_upload_ad.display_upload_product_type,ad_group_ad.ad.display_upload_ad.media_bundle,
           ad_group_ad.ad.display_url,ad_group_ad.ad.expanded_dynamic_search_ad.description,
           ad_group_ad.ad.expanded_dynamic_search_ad.description2,ad_group_ad.ad.expanded_text_ad.description,
           ad_group_ad.ad.expanded_text_ad.description2,ad_group_ad.ad.expanded_text_ad.headline_part1,
           ad_group_ad.ad.expanded_text_ad.headline_part2,ad_group_ad.ad.expanded_text_ad.headline_part3,
           ad_group_ad.ad.expanded_text_ad.path1,ad_group_ad.ad.expanded_text_ad.path2,
           ad_group_ad.ad.final_app_urls,ad_group_ad.ad.final_mobile_urls,ad_group_ad.ad.final_url_suffix,
           ad_group_ad.ad.final_urls,ad_group_ad.ad.gmail_ad.header_image,ad_group_ad.ad.gmail_ad.marketing_image,
           ad_group_ad.ad.gmail_ad.marketing_image_description,ad_group_ad.ad.gmail_ad.marketing_image_display_call_to_action.text,
           ad_group_ad.ad.gmail_ad.marketing_image_display_call_to_action.text_color,
           ad_group_ad.ad.gmail_ad.marketing_image_display_call_to_action.url_collection_id,
           ad_group_ad.ad.gmail_ad.marketing_image_headline,ad_group_ad.ad.gmail_ad.product_images,
           ad_group_ad.ad.gmail_ad.product_videos,ad_group_ad.ad.gmail_ad.teaser.business_name,
           ad_group_ad.ad.gmail_ad.teaser.description,ad_group_ad.ad.gmail_ad.teaser.headline,
           ad_group_ad.ad.gmail_ad.teaser.logo_image,ad_group_ad.ad.hotel_ad,ad_group_ad.ad.id,
           ad_group_ad.ad.image_ad.image_url,ad_group_ad.ad.image_ad.mime_type,ad_group_ad.ad.image_ad.name,
           ad_group_ad.ad.image_ad.pixel_height,ad_group_ad.ad.image_ad.pixel_width,
           ad_group_ad.ad.image_ad.preview_image_url,ad_group_ad.ad.image_ad.preview_pixel_height,
           ad_group_ad.ad.image_ad.preview_pixel_width,ad_group_ad.ad.legacy_app_install_ad,
           ad_group_ad.ad.legacy_responsive_display_ad.accent_color,
           ad_group_ad.ad.legacy_responsive_display_ad.allow_flexible_color,
           ad_group_ad.ad.legacy_responsive_display_ad.business_name,
           ad_group_ad.ad.legacy_responsive_display_ad.call_to_action_text,
           ad_group_ad.ad.legacy_responsive_display_ad.description,
           ad_group_ad.ad.legacy_responsive_display_ad.format_setting,
           ad_group_ad.ad.legacy_responsive_display_ad.logo_image,
           ad_group_ad.ad.legacy_responsive_display_ad.long_headline,
           ad_group_ad.ad.legacy_responsive_display_ad.main_color,
           ad_group_ad.ad.legacy_responsive_display_ad.marketing_image,
           ad_group_ad.ad.legacy_responsive_display_ad.price_prefix,ad_group_ad.ad.legacy_responsive_display_ad.promo_text,
           ad_group_ad.ad.legacy_responsive_display_ad.short_headline,ad_group_ad.ad.legacy_responsive_display_ad.square_logo_image,
           ad_group_ad.ad.legacy_responsive_display_ad.square_marketing_image,ad_group_ad.ad.local_ad.call_to_actions,
           ad_group_ad.ad.local_ad.descriptions,ad_group_ad.ad.local_ad.headlines,ad_group_ad.ad.local_ad.logo_images,
           ad_group_ad.ad.local_ad.marketing_images,ad_group_ad.ad.local_ad.path1,ad_group_ad.ad.local_ad.path2,
           ad_group_ad.ad.local_ad.videos,ad_group_ad.ad.name,ad_group_ad.ad.resource_name,ad_group_ad.ad.responsive_display_ad.accent_color,
           ad_group_ad.ad.responsive_display_ad.allow_flexible_color,ad_group_ad.ad.responsive_display_ad.business_name,
           ad_group_ad.ad.responsive_display_ad.call_to_action_text,ad_group_ad.ad.responsive_display_ad.control_spec.enable_asset_enhancements,
           ad_group_ad.ad.responsive_display_ad.control_spec.enable_autogen_video,ad_group_ad.ad.responsive_display_ad.descriptions,
           ad_group_ad.ad.responsive_display_ad.format_setting,ad_group_ad.ad.responsive_display_ad.headlines,
           ad_group_ad.ad.responsive_display_ad.logo_images,ad_group_ad.ad.responsive_display_ad.long_headline,
           ad_group_ad.ad.responsive_display_ad.main_color,ad_group_ad.ad.responsive_display_ad.marketing_images,
           ad_group_ad.ad.responsive_display_ad.price_prefix,ad_group_ad.ad.responsive_display_ad.promo_text,
           ad_group_ad.ad.responsive_display_ad.square_logo_images,ad_group_ad.ad.responsive_display_ad.square_marketing_images,
           ad_group_ad.ad.responsive_display_ad.youtube_videos,ad_group_ad.ad.responsive_search_ad.descriptions,
           ad_group_ad.ad.responsive_search_ad.headlines,ad_group_ad.ad.responsive_search_ad.path1,
           ad_group_ad.ad.responsive_search_ad.path2,ad_group_ad.ad.shopping_comparison_listing_ad.headline,
           ad_group_ad.ad.shopping_product_ad,ad_group_ad.ad.shopping_smart_ad,ad_group_ad.ad.smart_campaign_ad.descriptions,
           ad_group_ad.ad.smart_campaign_ad.headlines,ad_group_ad.ad.system_managed_resource_source,
           ad_group_ad.ad.text_ad.description1,ad_group_ad.ad.text_ad.description2,ad_group_ad.ad.text_ad.headline,
           ad_group_ad.ad.tracking_url_template,ad_group_ad.ad.type,ad_group_ad.ad.url_collections,
           ad_group_ad.ad.url_custom_parameters,ad_group_ad.ad.video_ad.bumper.companion_banner.asset,
           ad_group_ad.ad.video_ad.in_feed.description1,ad_group_ad.ad.video_ad.in_feed.description2,
           ad_group_ad.ad.video_ad.in_feed.headline,ad_group_ad.ad.video_ad.in_feed.thumbnail,
           ad_group_ad.ad.video_ad.in_stream.action_button_label,ad_group_ad.ad.video_ad.in_stream.action_headline,
           ad_group_ad.ad.video_ad.in_stream.companion_banner.asset,ad_group_ad.ad.video_ad.non_skippable.action_button_label,
           ad_group_ad.ad.video_ad.non_skippable.action_headline,ad_group_ad.ad.video_ad.non_skippable.companion_banner.asset,
           ad_group_ad.ad.video_ad.out_stream.description,ad_group_ad.ad.video_ad.out_stream.headline,ad_group_ad.ad.video_ad.video.asset,
           ad_group_ad.ad.video_responsive_ad.breadcrumb1,ad_group_ad.ad.video_responsive_ad.breadcrumb2,ad_group_ad.ad.video_responsive_ad.call_to_actions,
           ad_group_ad.ad.video_responsive_ad.companion_banners,ad_group_ad.ad.video_responsive_ad.descriptions,ad_group_ad.ad.video_responsive_ad.headlines,
           ad_group_ad.ad.video_responsive_ad.long_headlines,ad_group_ad.ad.video_responsive_ad.videos,ad_group_ad.ad_group,ad_group_ad.ad_strength,
           ad_group_ad.labels,ad_group_ad.policy_summary.approval_status,ad_group_ad.policy_summary.policy_topic_entries,
           ad_group_ad.policy_summary.review_status,ad_group_ad.resource_name,ad_group_ad.status 
    FROM ad_group_ad"""
stream = googleads_service.search_stream(customer_id=customerId, query=query)

for batch in stream:
    for row in batch.results:
        data.append(json_format.MessageToDict(row))

    print(f"Current count = {len(data)}")

print(f"Finished")
```

After fetching 1740000 I get this error
```
Request made: ClientCustomerId: XXX, Host: googleads.googleapis.com, Method: /google.ads.googleads.v10.services.GoogleAdsService/SearchStream, RequestId: None, IsFault: True, FaultMessage: Received message larger than max (80521595 vs. 67108864)
Traceback (most recent call last):
  File "C:\Workspace\sandbox\venv\lib\site-packages\google\api_core\grpc_helpers.py", line 97, in __next__
    return next(self._wrapped)
  File "C:\Workspace\sandbox\venv\lib\site-packages\google\ads\googleads\interceptors\response_wrappers.py", line 108, in __next__
    raise e
  File "C:\Workspace\sandbox\venv\lib\site-packages\google\ads\googleads\interceptors\response_wrappers.py", line 105, in __next__
    self._failure_handler(self._underlay_call)
  File "C:\Workspace\sandbox\venv\lib\site-packages\google\ads\googleads\interceptors\exception_interceptor.py", line 71, in _handle_grpc_failure
    raise self._get_error_from_response(response)
  File "C:\Workspace\sandbox\venv\lib\site-packages\google\ads\googleads\interceptors\response_wrappers.py", line 88, in __next__
    message = next(self._underlay_call)
  File "C:\Workspace\sandbox\venv\lib\site-packages\grpc\_channel.py", line 426, in __next__
    return self._next()
  File "C:\Workspace\sandbox\venv\lib\site-packages\grpc\_channel.py", line 642, in _next
    return self._next_response()
  File "C:\Workspace\sandbox\venv\lib\site-packages\grpc\_channel.py", line 617, in _next_response
    raise self
grpc._channel._SingleThreadedRendezvous: <_SingleThreadedRendezvous of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Received message larger than max (80521595 vs. 67108864)"
	debug_error_string = "{"created":"@1655280925.357000000","description":"Error received from peer ipv4:142.250.200.10:443","file":"src/core/lib/surface/call.cc","file_line":953,"grpc_message":"Received message larger than max (80521595 vs. 67108864)","grpc_status":8}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Workspace\sandbox\venv\lib\site-packages\google\api_core\grpc_helpers.py", line 100, in __next__
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Received message larger than max (80521595 vs. 67108864)

Process finished with exit code 1
```

**Expected behavior:**
All ad group ads will be fetched

**Client library version and API version:**
Client library version: 16.0.0
Google Ads API version: 2.7.3

aiohttp==3.8.1
aiosignal==1.2.0    
async-timeout==4.0.2
attrs==21.4.0
cachetools==5.0.0
certifi==2021.10.8
charset-normalizer==2.0.12
click==8.1.3
colorama==0.4.4
curlify==2.2.1
frozenlist==1.3.0
google-ads==16.0.0
google-api-core==2.7.3
google-auth==2.6.6
google-auth-oauthlib==0.5.1
googleapis-common-protos==1.56.0
greenlet==1.1.2
grpcio==1.46.1
grpcio-status==1.46.1
idna==3.3
mongoengine==0.24.1
mongomock==4.0.0
multidict==6.0.2
oauthlib==3.2.0
orjson==3.6.8
packaging==21.3
proto-plus==1.19.6
protobuf==3.20.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycountry==22.3.5
pymongo==4.1.1
pyparsing==3.0.9
pyperclip==1.8.2
PyYAML==5.4.1
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.8
sentinels==1.0.0
six==1.16.0
SQLAlchemy==1.4.36
ujson==5.2.0
uncurl==0.0.11
urllib3==1.26.9
yarl==1.7.2

I saw in the .NET library you can set MaxReceiveMessageLengthInBytes and MaxMetadataSizeInBytes but not in python.
What can I do here?

**Comment by bobhancock** [comment]
The settings in .Net would not help with this error. You need to reduce the number of columns returned in the response. You can break the query into two queries and aggregate the results.

**Comment by BenRKarl** [comment]
@Kremzon this library sets both message sizes to be 16MB [here](https://github.com/googleads/google-ads-python/blob/main/google/ads/googleads/client.py#L51). We don't recommend trying to adjust this value, as @bobhancock mentioned the best approach is to reduce your query size and aggregate results as needed.
