### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'  

### ISSUE THREAD

**Issue by jimmyVadako** [googleads/google-ads-python#666]
I installed latest version google-ads==17.0.0 in Windows
When trying to run this script I got this:
```
python.exe "D:/v/CR/get_view.py"
Traceback (most recent call last):
  File "D:\v\CR\get_geographic_view.py", line 5, in <module>
    **from google.ads.googleads.client import GoogleAdsClient**
  File "C:\Users\U\AppData\Local\Programs\Python\Python310\lib\site-packages\google\ads\googleads\__init__.py", line 15, in <module>
    import google.ads.googleads.client
  File "C:\Users\U\AppData\Local\Programs\Python\Python310\lib\site-packages\google\ads\googleads\client.py", line 20, in <module>
    from google.api_core.gapic_v1.client_info import ClientInfo
  File "C:\Users\U\AppData\Local\Programs\Python\Python310\lib\site-packages\google\api_core\gapic_v1\__init__.py", line 16, in <module>
    from google.api_core.gapic_v1 import config
  File "C:\Users\U\AppData\Local\Programs\Python\Python310\lib\site-packages\google\api_core\gapic_v1\config.py", line 25, in <module>
    from google.api_core import exceptions
  File "C:\Users\U\AppData\Local\Programs\Python\Python310\lib\site-packages\google\api_core\exceptions.py", line 29, in <module>
    from google.rpc import error_details_pb2
  File "C:\Users\U\AppData\Local\Programs\Python\Python310\lib\site-packages\google\rpc\error_details_pb2.py", line 39, in <module>
    _RETRYINFO = DESCRIPTOR.message_types_by_name["RetryInfo"]
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'  
```

**Comment by andrei-shabanski** [comment]
I got the same error in google-ads 17.0.0
Installing the latest version of protobuf==4.21.2 resolves it, but google-ads v17 officially depends on protobuf (>=3.12.0,<3.18.0 || 3.20.0) only

**Comment by BenRKarl** [comment]
Thanks @andrei-shabanski
