### ISSUE TITLE
Error getting campaign info - ipykernel_launcher.py: error: the following arguments are required: -c/--6188728766

### ISSUE THREAD

**Issue by KicksTerz** [googleads/google-ads-python#690]
Hello,
I get the following error when I try to get campaign info.
Describe the bug:
```
usage: ipykernel_launcher.py [-h] -c 6188728766
ipykernel_launcher.py: error: the following arguments are required: -c/--6188728766
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
```
Steps to Reproduce
```
import argparse
import sys

from google.ads.googleads.client import GoogleAdsClient
from google.ads.googleads.errors import GoogleAdsException


def main(client, customer_id):
    ga_service = client.get_service("GoogleAdsService")

    query = """
        SELECT
          campaign.id,
          campaign.name
        FROM campaign
        ORDER BY campaign.id"""

    # Issues a search request using streaming.
    stream = ga_service.search_stream(customer_id=customer_id, query=query)

    for batch in stream:
        for row in batch.results:
            print(
                f"Campaign with ID {row.campaign.id} and name "
                f'"{row.campaign.name}" was found.'
            )


if __name__ == "__main__":
    # GoogleAdsClient will read the google-ads.yaml configuration file in the
    # home directory if none is specified.
    googleads_client = GoogleAdsClient.load_from_storage("./google-ads.yaml")

    parser = argparse.ArgumentParser(
        description="Lists all campaigns for specified customer."
    )
    # The following argument(s) should be provided to run the example.
    parser.add_argument(
        "-c",
        "--6188728766",
        type=str,
        required=True,
        help="The Google Ads customer ID.",
    )
    args = parser.parse_args()

    try:
        main(googleads_client, args.customer_id)
    except GoogleAdsException as ex:
        print(
            f'Request with ID "{ex.request_id}" failed with status '
            f'"{ex.error.code().name}" and includes the following errors:'
        )
        for error in ex.failure.errors:
            print(f'\tError with message "{error.message}".')
            if error.location:
                for field_path_element in error.location.field_path_elements:
                    print(f"\t\tOn field: {field_path_element.field_name}")
        sys.exit(1)
```
Expected behavior:
`Campaign with ID xxxxxxxxxxx and name "Campaign-Name-1" was found.`

Versions:
```
google-ads                   18.0.0
google-api-core              2.8.2
google-auth                  1.35.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
googleads                    33.0.0
googleapis-common-protos     1.56.4
```
The updated yaml file is in the root directory of the project containing the following info:
```
developer_token
client_id
client_secret
refresh_token
login_customer_id
```

The project runs in a docker container.

**Comment by BenRKarl** [comment]
@KicksTerz It's not clear what the issue is here, since the error is stemming from your script `ipykernel_launcher.py`. Could you share a more complete stack trace?

**Comment by KicksTerz** [comment]
Hi, @BenRKarl,
Please find below further info regarding the issue:

```
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?299df0bc-8379-4650-9cf0-217648f153ee)
---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
/workspaces/GoogleAdsApi/test.ipynb Cell 10 in <cell line: 49>()
     [57](vscode-notebook-cell://dev-container%2B633a5c55736572735c557365725c446f63756d656e74735c507974686f6e5c476f6f676c65416473417069/workspaces/GoogleAdsApi/test.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=56) # The following argument(s) should be provided to run the example.
     [58](vscode-notebook-cell://dev-container%2B633a5c55736572735c557365725c446f63756d656e74735c507974686f6e5c476f6f676c65416473417069/workspaces/GoogleAdsApi/test.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=57) parser.add_argument(
     [59](vscode-notebook-cell://dev-container%2B633a5c55736572735c557365725c446f63756d656e74735c507974686f6e5c476f6f676c65416473417069/workspaces/GoogleAdsApi/test.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=58)     "-c",
     [60](vscode-notebook-cell://dev-container%2B633a5c55736572735c557365725c446f63756d656e74735c507974686f6e5c476f6f676c65416473417069/workspaces/GoogleAdsApi/test.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=59)     "--6188728766",
   (...)
     [63](vscode-notebook-cell://dev-container%2B633a5c55736572735c557365725c446f63756d656e74735c507974686f6e5c476f6f676c65416473417069/workspaces/GoogleAdsApi/test.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=62)     help="The Google Ads customer ID.",
     [64](vscode-notebook-cell://dev-container%2B633a5c55736572735c557365725c446f63756d656e74735c507974686f6e5c476f6f676c65416473417069/workspaces/GoogleAdsApi/test.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=63) )
---> [65](vscode-notebook-cell://dev-container%2B633a5c55736572735c557365725c446f63756d656e74735c507974686f6e5c476f6f676c65416473417069/workspaces/GoogleAdsApi/test.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=64) args = parser.parse_args()
     [67](vscode-notebook-cell://dev-container%2B633a5c55736572735c557365725c446f63756d656e74735c507974686f6e5c476f6f676c65416473417069/workspaces/GoogleAdsApi/test.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=66) try:
     [68](vscode-notebook-cell://dev-container%2B633a5c55736572735c557365725c446f63756d656e74735c507974686f6e5c476f6f676c65416473417069/workspaces/GoogleAdsApi/test.ipynb#X12sdnNjb2RlLXJlbW90ZQ%3D%3D?line=67)     main(googleads_client, args.customer_id)

File /usr/local/lib/python3.9/argparse.py:1825, in ArgumentParser.parse_args(self, args, namespace)
   1824 def parse_args(self, args=None, namespace=None):
-> 1825     args, argv = self.parse_known_args(args, namespace)
   1826     if argv:
   1827         msg = _('unrecognized arguments: %s')

File /usr/local/lib/python3.9/argparse.py:1858, in ArgumentParser.parse_known_args(self, args, namespace)
   1856 if self.exit_on_error:
   1857     try:
-> 1858         namespace, args = self._parse_known_args(args, namespace)
   1859     except ArgumentError:
...
   2567 if message:
   2568     self._print_message(message, _sys.stderr)
-> 2569 _sys.exit(status)

SystemExit: 2
```

Many thanks,

**Comment by BenRKarl** [comment]
Ah I see the problem now - looks like you've passed your customer ID into the call to `add_argument`, which defines a command line argument and can't be used to pass arguments. [Here](https://github.com/googleads/google-ads-python/blob/main/examples/basic_operations/get_campaigns.py#L60) is how it should look, note that `-c` is shorthand for `--customer_id`.

The intended way to pass your customer ID is via a command line argument, so when executing the script you would run:

```
python examples/basic_operations/get_campaigns.py -c 6188728766
```

I'm not sure how your script works, but it might look something like this:

```
python ipykernel_launcher.py -c 6188728766
```

If you can't get the command line args to work, then you can always hardcode the customer ID into the call to the `main` function like this:

```py
    try:
        main(googleads_client, "6188728766")
    except GoogleAdsException as ex:
        ...
```

But since the `customer_id` argument is required, you'll also need to mark it as optional:

```py
    parser.add_argument(
        "-c",
        "--customer_id",
        type=str,
        required=False,
        help="The Google Ads customer ID.",
    )
```

My recommendation is to use the command line argument.

**Comment by KicksTerz** [comment]
Hi @BenRKarl,
Sorry to insist after you've closed the thread, but the issue persists on my side.
Neither of the solutions work, I always get the following error message, despite my google-ads.yaml file being located in the root directory:
```
root@1eda5961b0f5:/workspaces/GoogleAdsApi/google-ads-python-main/examples/basic_operations# python get_campaigns.py -c 6188728766
Traceback (most recent call last):
  File "/workspaces/GoogleAdsApi/google-ads-python-main/examples/basic_operations/get_campaigns.py", line 52, in <module>
    googleads_client = GoogleAdsClient.load_from_storage(version="v18")
  File "/usr/local/lib/python3.9/site-packages/google/ads/googleads/client.py", line 289, in load_from_storage
    config_data = config.load_from_yaml_file(path)
  File "/usr/local/lib/python3.9/site-packages/google/ads/googleads/config.py", line 69, in validation_wrapper
    config_dict = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/google/ads/googleads/config.py", line 87, in parser_wrapper
    config_dict = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/google/ads/googleads/config.py", line 271, in load_from_yaml_file
    with open(path, "rb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/root/google-ads.yaml'
```

File configuration with "hardcoded" client ID.
```
parser.add_argument(
        "-c",
        "--customer_id",
        type=str,
        required=False,
        help="The Google Ads customer ID.",
    )
    args = parser.parse_args()

    try:
        main(googleads_client, "6188728766")
```

And the get_campaigns.py file by just using the command line argument:
```
googleads_client = GoogleAdsClient.load_from_storage(version="v18")

    parser = argparse.ArgumentParser(
        description="Lists all campaigns for specified customer."
    )
    # The following argument(s) should be provided to run the example.
    parser.add_argument(
        "-c",
        "--customer_id",
        type=str,
        required=True,
        help="The Google Ads customer ID.",
    )
    args = parser.parse_args()

    try:
        main(googleads_client, args.customer_id)
```

**Comment by BloggingKIng** [comment]
From the given error message it's clear that you haven't provided the correct path to the **google-ads.yaml** file! You should check your path again if it is correct or not. Or you can just provide the direct path to the google-ads.yaml file instead of relative path!

**Comment by KicksTerz** [comment]
Hi @BloggingKIng,
It worked indeed when I used an absolute path instead of a relative one, thank you for your help.
Still, go easy with those exclamation marks.

**Comment by BloggingKIng** [comment]
Glad that it worked. And yes using these exclamation marks is just an unintentional/routine thing for me :)

**Comment by BenRKarl** [comment]
@BloggingKIng thanks for jumping into help, @KicksTerz let us know if you run into any other issues.
