### ISSUE TITLE
Intermittent "ServiceUnavailable: 503 failed to connect to all addresses"

### ISSUE THREAD

**Issue by alexnbferreira** [googleads/google-ads-python#748]
**Describe the bug:**
When using google-ads module to do some keyword reporting, running some queries using search_stream will, for some of our client IDs, return a 503 Service Unavailable error. It doesn't contain much information in the error message but I will paste it underneath. I contacted the Google Ads API team and they redirected me back to this page.

**Steps to Reproduce:**
One of the queries that is triggering this error a lot of times is the following (replacing dates with proper values and giving it a list of keywords resource names to filter, 500 at a time)
"""
      SELECT
          keyword_view.resource_name,
          customer.currency_code,
          customer.time_zone,
          customer.resource_name,
          ad_group.id,
          ad_group.name,
          -- bidding_strategy.type,
          campaign.id,
          ad_group_criterion.keyword.text,
          customer.id,
          ad_group_criterion.criterion_id,
          ad_group_criterion.negative,
          ad_group_criterion.keyword.match_type,
          ad_group_criterion.status,
          ad_group_criterion.labels,
          ad_group_criterion.system_serving_status,
          segments.date,
          segments.ad_network_type,
          segments.device,
          -- segments.slot,
          metrics.impressions,
          metrics.clicks,
          metrics.conversions,
          metrics.cost_micros,
          metrics.search_impression_share
          FROM keyword_view
          WHERE segments.date BETWEEN "{0}" AND "{1}"
          AND ad_group_criterion.negative = 'FALSE'
          AND ad_group_criterion.keyword.text IS NOT NULL
          AND metrics.impressions > 0
          AND keyword_view.resource_name IN {2}
          """
**Expected behavior:**
I expect the search_stream function to  return the data I am looking for. Most times (and before this happened, everytime) it would. After upgrading the google-ads api version to V12 these errors increased in number.

**Client library version and API version:**
GoogleAPI V12 being used. .

Pip Freeze:
appdirs==1.4.4
asn1crypto==1.5.1
attrs==22.2.0
boto3==1.26.75
botocore==1.29.75
cached-property==1.5.2
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
cryptography==39.0.1
defusedxml==0.7.1
filelock==3.9.0
google-ads==19.0.0
google-api-core==2.10.1
google-auth==2.16.1
google-auth-oauthlib==0.8.0
googleads-reporting @ file:///googleads_reporting-1.2.0.tar.gz
googleapis-common-protos==1.58.0
grpcio==1.51.1
grpcio-status==1.51.1
idna==3.4
isodate==0.6.1
jmespath==1.0.1
lxml==4.9.2
numpy==1.24.2
oauthlib==3.2.2
oscrypto==1.3.0
pandas==1.5.3
proto-plus==1.22.1
protobuf==4.22.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pycryptodomex==3.17
PyJWT==2.6.0
pyOpenSSL==23.0.0
python-dateutil==2.8.2
pytz==2022.7.1
PyYAML==6.0
requests==2.28.2
requests-oauthlib==1.3.1
requests-toolbelt==0.10.1
rsa==4.9
s3transfer==0.6.0
six==1.16.0
snowflake-connector-python==3.0.0
typing_extensions==4.5.0
urllib3==1.26.14
zeep==3.4.0

**Request/Response Logs:**
The error logs I get when I find this error 

`File "/usr/local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 162, in error_remapped_callable
 return _StreamingResponseIterator(
File "/usr/local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 88, in __init__
 self._stored_first_result = next(self._wrapped)
File "/usr/local/lib/python3.8/site-packages/google/ads/googleads/interceptors/response_wrappers.py", line 108, in __next__
 raise e
File "/usr/local/lib/python3.8/site-packages/google/ads/googleads/interceptors/response_wrappers.py", line 105, in __next__
 self._failure_handler(self._underlay_call)
File "/usr/local/lib/python3.8/site-packages/google/ads/googleads/interceptors/exception_interceptor.py", line 71, in _handle_grpc_failure
 raise self._get_error_from_response(response)
File "/usr/local/lib/python3.8/site-packages/google/ads/googleads/interceptors/response_wrappers.py", line 88, in __next__
 message = next(self._underlay_call)
File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
 return self._next()
File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 642, in _next
 return self._next_response()
File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 617, in _next_response
 raise self
grpc._channel._SingleThreadedRendezvous: <_SingleThreadedRendezvous of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B2a00:1450:400b:c01::5f%5D:443: Network is unreachable"
debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B2a00:1450:400b:c01::5f%5D:443: Network is unreachable {created_time:"2023-02-21T08:13:19.544892283+00:00", grpc_status:14}"
>
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "main.py", line 76, in <module>
 results = do_job(report_to_run, args)
File "main.py", line 24, in do_job
 results = report_function(args=args)
File "/reports.py", line 328, in generate_keyword_performance_report
 report = report_googleads_keywords_performance_database(client, ent, date_from, date_to)
File "/usr/local/lib/python3.8/site-packages/googleads_reporting/report.py", line 116, in report_googleads_keywords_performance_database
 df_final1 = return_report(client=client, customer_id=customer_id, query=query1)
File "/usr/local/lib/python3.8/site-packages/googleads_reporting/report.py", line 317, in return_report
 stream = ga_service.search_stream(customer_id=customer_id, query=query)
File "/usr/local/lib/python3.8/site-packages/google/ads/googleads/v12/services/services/google_ads_service/client.py", line 3475, in search_stream
 response = rpc(
File "/usr/local/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
 return wrapped_func(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 166, in error_remapped_callable
 raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B2a00:1450:400b:c01::5f%5D:443: Network is unreachable`

 
**Anything else we should know about your project / environment:**
This code is running on a Docker image on AWS Fargate
![code](https://user-images.githubusercontent.com/11177119/220336552-67ef9d4c-f201-4500-b066-238ba827258d.png)
![code2](https://user-images.githubusercontent.com/11177119/220336555-b34a2db9-0d77-4dc8-be28-3d5db0a55f5d.png)

**Comment by BenRKarl** [comment]
@alexnbferreira those logs appear to be at the gRPC-level, meaning the request doesn't appear to even reach the API. At first glance it appears to be a network connectivity issue. Is it possible for you to rule out a firewall or other network configuration blocking outgoing requests?

**Comment by alexnbferreira** [comment]
Hi @BenRKarl  thanks for the reply. These tasks are Docker images running on the Amazon Fargate platform. There is no special network configuration, it has a security group attached granting it full access to the outside internet. I have this same report repeated for our multiple ad accounts, and I only seem to have this problem with some of them. The ones that don't run successfully everytime

**Comment by BenRKarl** [comment]
@alexnbferreira thanks for the details and apologies for the delayed response. Just wondering if you're still having these issues. I haven't been able to pinpoint a root cause, and I'm wondering if it was transient and has since resolved itself.
