### ISSUE TITLE
`generate_keyword_ideas.py` has some errors.

### ISSUE THREAD

**Issue by taako-502** [googleads/google-ads-python#773]
## What I did:
I ran this command:
`python examples/planning/generate_keyword_ideas.py -c {JSON file path} -k {keywords} --customer_id {customer id}`

## Whats happend
The above command caused the following error:
```bash
google-ads-python % python examples/planning/generate_keyword_ideas.py -c client_secret_9999-hogehoge.apps.googleusercontent.com.json -k "test" --customer_id 9999999999

Traceback (most recent call last):
  File "/Users/takao/GitHub/google-ads-python/examples/planning/generate_keyword_ideas.py", line 176, in <module>
    main(
  File "/Users/takao/GitHub/google-ads-python/examples/planning/generate_keyword_ideas.py", line 64, in main
    request.geo_target_constants = location_rns
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Assignment not allowed to message, map, or repeated field "geo_target_constants" in protocol message object.
```

I modified `generate_keyword_ideas.py` as follows:
```Python
# request.geo_target_constants = location_rns
request.geo_target_constants.extend(location_rns)
```

Then, the following error occurred:
```bash
google-ads-python % python examples/planning/generate_keyword_ideas.py -c client_secret_9999-hogehoge.apps.googleusercontent.com.json -k "test" --customer_id 9999999999

Traceback (most recent call last):
  File "/Users/takao/GitHub/google-ads-python/examples/planning/generate_keyword_ideas.py", line 176, in <module>
    main(
  File "/Users/takao/GitHub/google-ads-python/examples/planning/generate_keyword_ideas.py", line 91, in main
    competition_value = idea.keyword_idea_metrics.competition.name
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'name'
```

I made further modifications as follows:
```Python
# competition_value = idea.keyword_idea_metrics.competition.name
competition_value = idea.keyword_idea_metrics.competition
```

It worked well.
```bash
google-ads-python % python examples/planning/generate_keyword_ideas.py -c client_secret_9999-hogehoge.apps.googleusercontent.com.json -k "test" --customer_id 9999999999

Keyword idea text "test" has "301000" average monthly searches and "2" competition.

Keyword idea text "speed test" has "368000" average monthly searches and "2" competition.

Keyword idea text "internet speed test" has "135000" average monthly searches and "2" competition.

Keyword idea text "wifi speed test" has "27100" average monthly searches and "2" competition.

Keyword idea text "net speed test" has "4400" average monthly searches and "2" competition.

Keyword idea text "speedtest ookla" has "12100" average monthly searches and "2" competition.

Keyword idea text "typing speed test" has "5400" average monthly searches and "2" competition.

Keyword idea text "net speed" has "1300" average monthly searches and "2" competition.

Keyword idea text "broadband speed test" has "720" average monthly searches and "2" competition.
```

## Reference article
https://tosix.work/ads-api-test/

**Comment by taako-502** [comment]
@BenRKarl 
I changed use_proto_plus to True and ran the command.
The command was successful.

Very thank you!!!
